### ISSUE TITLE
MongoDB URL variable name missmatch

### ISSUE THREAD

**Issue by iamharshil** [iamharshil/express-api-template#4]
Variable name from environment variable and inside database.config.ts both are different.

**Comment by Sathurshanan-Kandhasamy** [comment]
Hi @iamharshil, can I work on this issue?

**Comment by iamharshil** [comment]
> Hi @iamharshil, can I work on this issue?

Hey @Sathurshanan-Kandhasamy, Yes you can fix this issue it would be great .!!😊, make sure to create new branch and push your code there.

**Comment by iamharshil** [comment]
Fixed it in new update
